"""Build-time script: extract <synapses> from virtuoso.xml → synapses.ts.

Run from repo root:
    python wakeel/scripts/extract_synapses.py

Outputs:
  wakeel/edge/src/synapses.ts  — exported string constant, bundled into Worker

Reads from: virtuoso/ (read-only)
Writes to:  wakeel/edge/src/ (only)
"""
from __future__ import annotations

import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO_ROOT = Path(__file__).parents[2]
VIRTUOSO_XML = REPO_ROOT / "virtuoso" / "virtuoso.xml"
OUT_TS = REPO_ROOT / "wakeel" / "edge" / "src" / "synapses.ts"

SENTINEL = "VERIFY, DON'T TRUST"


def main() -> None:
    if not VIRTUOSO_XML.exists():
        print(f"ERROR: {VIRTUOSO_XML} not found", file=sys.stderr)
        sys.exit(1)

    tree = ET.parse(str(VIRTUOSO_XML))
    root = tree.getroot()
    synapses_el = root.find("synapses")
    if synapses_el is None:
        print("ERROR: <synapses> block not found in virtuoso.xml", file=sys.stderr)
        sys.exit(1)

    content = ET.tostring(synapses_el, encoding="unicode")

    if SENTINEL not in content:
        print(
            f"ERROR: integrity check failed — '{SENTINEL}' sentinel not found in synapses block",
            file=sys.stderr,
        )
        sys.exit(1)

    # Escape backticks so the TS template literal is valid
    escaped = content.replace("`", "\\`").replace("${", "\\${")

    ts_output = (
        "// Auto-generated by extract_synapses.py — do not edit manually\n"
        f"export const SYNAPSES = `{escaped}`;\n"
    )

    OUT_TS.parent.mkdir(parents=True, exist_ok=True)
    OUT_TS.write_text(ts_output, encoding="utf-8")
    print(f"synapses.ts: {len(content):,} chars, sentinel OK")


if __name__ == "__main__":
    main()
